parameters:
#    mesd_doctrine_extensions_datefunctions.example.class: MESD\DoctrineExtensions\DateFunctionsBundle\Example

services:
#    mesd_doctrine_extensions_datefunctions.example:
#        class: %mesd_doctrine_extensions_datefunctions.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]